<Project>
  <PropertyGroup>
    <AnalysisLevel>10</AnalysisLevel>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
