<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Shift.Ipc/Shift.Ipc.csproj" />
    <ProjectReference Include="../Shift.Protocol/Shift.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Shift.Archiver.Tests" />
  </ItemGroup>
</Project>
